name: iOS e2e tests

on:
  push:
    branches: [ try/github-actions-ios-ci ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Restore npm cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: |
        source ~/.nvm/nvm.sh
        nvm install
        npm ci

    - name: Prepare build cache key
      run: find package-lock.json packages/react-native-editor/ios packages/react-native-aztec/ios packages/react-native-bridge/ios -type f -print0 | sort -z | xargs -0 shasum | tee ios-checksums.txt

    - name: Restore build cache
      uses: actions/cache@v1
      with:
        path: packages/react-native-editor/ios/build/gutenberg/Build/Products/Release-iphonesimulator/GutenbergDemo.app
        key: ${{ runner.os }}-ios-build-${{ hashFiles('ios-checksums.txt') }}
    
    - name: Restore pods cache
      uses: actions/cache@master
      with:
        path: |
          packages/react-native-editor/ios/Pods
          ~/Library/Caches/CocoaPods
          ~/.cocoapods/repos/trunk
          packages/react-native-editor/ios/vendor
        key: ${{ runner.os }}-pods-${{ hashFiles('packages/react-native-editor/ios/Gemfile.lock') }}-${{ hashFiles('packages/react-native-editor/ios/Podfile.lock') }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-pods-${{ hashFiles('packages/react-native-editor/ios/Gemfile.lock') }}-${{ hashFiles('packages/react-native-editor/ios/Podfile.lock') }}-${{ hashFiles('package-lock.json') }}
          ${{ runner.os }}-pods-${{ hashFiles('packages/react-native-editor/ios/Gemfile.lock') }}-${{ hashFiles('packages/react-native-editor/ios/Podfile.lock') }}-
          ${{ runner.os }}-pods-${{ hashFiles('packages/react-native-editor/ios/Gemfile.lock') }}-
          ${{ runner.os }}-pods-

    - name: Bundle iOS
      run: npm run native test:e2e:bundle:ios

    - name: Build (if needed)
      run: test -e packages/react-native-editor/ios/build/gutenberg/Build/Products/Release-iphonesimulator/GutenbergDemo.app/GutenbergDemo || SKIP_BUNDLING=true npm run native test:e2e:build-app:ios

    - name: Run iOS Device Tests
      run: TEST_RN_PLATFORM=ios npm run native device-tests:local

    - name: Prepare build cache
      run: rm packages/react-native-editor/ios/build/gutenberg/Build/Products/Release-iphonesimulator/GutenbergDemo.app/main.jsbundle

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ios-screen-recordings
        path: packages/react-native-editor/ios-screen-recordings